name: Deploy to Rallway

on:
    push:
        branches: [main]

jobs:
    helloworld:
        runs-on: ubuntu-latest


        steps:
        - uses action/checkout@v4

        - name: Imprimir en consola
        run:
          echo "hello World, GITHUB ACTIONS"
          
